# Generated by Django 5.0.6 on 2024-08-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(choices=[(False, 'Приватный'), (True, 'Общий Доступ')], default=1)),
                ('priority', models.BooleanField(choices=[(False, 'Обычный'), (True, 'Повышенный')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
