# Generated by Django 5.0.6 on 2024-09-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='back',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/users/back/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/users/icon/%Y/%m/%d'),
        ),
    ]
